=== openMRSiDART/iDART/target-test/datasets/iDART.dtd
<!ELEMENT dataset (
    atccode*,
    form*,
    drug*,
    nationalclinics*,
    clinic*,
    package*,
    pillcount*,
    accumulateddrugs*,
    adherencerecordtmp*,
    alerts*,
    patient*,
    alternatepatientidentifier*,
    appointment*,
    chemicalcompound*,
    atccode_chemicalcompound*,
    attributetype*,
    campaign*,
    campaign_participant*,
    chemicaldrugstrength*,
    clinicuser*,
    databasechangelog*,
    databasechangeloglock*,
    deleteditem*,
    doctor*,
    episode*,
    identifiertype*,
    logging*,
    messageschedule*,
    packageddrugs*,
    users*,
    packagedruginfotmp*,
    patientattribute*,
    patientidentifier*,
    patientstatistic*,
    patientstattypes*,
    patientvisit*,
    patientvisitreason*,
    pregnancy*,
    prescription*,
    prescribeddrugs*,
    regimen*,
    regimendrugs*,
    simpledomain*,
    stockcenter*,
    stock*,
    stocktake*,
    stockadjustment*,
    stocklevel*,
    study*,
    studyparticipant*)>

<!ELEMENT atccode EMPTY>
<!ATTLIST atccode
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    code CDATA #REQUIRED
    mims CDATA #IMPLIED
>

<!ELEMENT form EMPTY>
<!ATTLIST form
    id CDATA #REQUIRED
    form CDATA #IMPLIED
    actionlanguage1 CDATA #IMPLIED
    actionlanguage2 CDATA #IMPLIED
    actionlanguage3 CDATA #IMPLIED
    formlanguage1 CDATA #IMPLIED
    formlanguage2 CDATA #IMPLIED
    formlanguage3 CDATA #IMPLIED
    dispinstructions1 CDATA #IMPLIED
    dispinstructions2 CDATA #IMPLIED
>

<!ELEMENT drug EMPTY>
<!ATTLIST drug
    id CDATA #REQUIRED
    form CDATA #REQUIRED
    dispensinginstructions1 CDATA #IMPLIED
    dispensinginstructions2 CDATA #IMPLIED
    modified CDATA #IMPLIED
    name CDATA #IMPLIED
    packsize CDATA #IMPLIED
    sidetreatment CDATA #IMPLIED
    defaultamnt CDATA #IMPLIED
    defaulttimes CDATA #IMPLIED
    stockcode CDATA #IMPLIED
    atccode_id CDATA #IMPLIED
>

<!ELEMENT nationalclinics EMPTY>
<!ATTLIST nationalclinics
    id CDATA #REQUIRED
    province CDATA #REQUIRED
    district CDATA #REQUIRED
    subdistrict CDATA #REQUIRED
    facilityname CDATA #REQUIRED
    facilitytype CDATA #REQUIRED
>

<!ELEMENT clinic EMPTY>
<!ATTLIST clinic
    id CDATA #REQUIRED
    notes CDATA #IMPLIED
    telephone CDATA #IMPLIED
    mainclinic CDATA #IMPLIED
    clinicname CDATA #IMPLIED
    clinicdetails_id CDATA #IMPLIED
>

<!ELEMENT package EMPTY>
<!ATTLIST package
    id CDATA #REQUIRED
    dateleft CDATA #IMPLIED
    datereceived CDATA #IMPLIED
    modified CDATA #IMPLIED
    packageid CDATA #IMPLIED
    packdate CDATA #IMPLIED
    pickupdate CDATA #IMPLIED
    prescription CDATA #IMPLIED
    weekssupply CDATA #IMPLIED
    datereturned CDATA #IMPLIED
    stockreturned CDATA #IMPLIED
    packagereturned CDATA #IMPLIED
    reasonforpackagereturn CDATA #IMPLIED
    clinic CDATA #IMPLIED
    drugtypes CDATA #IMPLIED
>

<!ELEMENT pillcount EMPTY>
<!ATTLIST pillcount
    id CDATA #REQUIRED
    accum CDATA #REQUIRED
    previouspackage CDATA #REQUIRED
    dateofcount CDATA #REQUIRED
    drug CDATA #REQUIRED
>

<!ELEMENT accumulateddrugs EMPTY>
<!ATTLIST accumulateddrugs
    id CDATA #REQUIRED
    withpackage CDATA #REQUIRED
    pillcount CDATA #REQUIRED
>

<!ELEMENT adherencerecordtmp EMPTY>
<!ATTLIST adherencerecordtmp
    id CDATA #REQUIRED
    adherencereason CDATA #IMPLIED
    countdate CDATA #IMPLIED
    dayscarriedover CDATA #IMPLIED
    daysinhand CDATA #IMPLIED
    dayssincevisit CDATA #IMPLIED
    dayssupplied CDATA #IMPLIED
    pawcno CDATA #IMPLIED
    pillcountid CDATA #IMPLIED
    cluser CDATA #IMPLIED
>

<!ELEMENT alerts EMPTY>
<!ATTLIST alerts
    id CDATA #REQUIRED
    alertmessage CDATA #REQUIRED
    alerttype CDATA #REQUIRED
    alertdate CDATA #REQUIRED
    void CDATA #IMPLIED
>

<!ELEMENT patient EMPTY>
<!ATTLIST patient
    id CDATA #REQUIRED
    accountstatus CDATA #IMPLIED
    cellphone CDATA #IMPLIED
    dateofbirth CDATA #IMPLIED
    clinic CDATA #REQUIRED
    firstnames CDATA #IMPLIED
    homephone CDATA #IMPLIED
    lastname CDATA #IMPLIED
    modified CDATA #IMPLIED
    patientid CDATA #REQUIRED
    province CDATA #IMPLIED
    sex CDATA #IMPLIED
    workphone CDATA #IMPLIED
    address1 CDATA #IMPLIED
    address2 CDATA #IMPLIED
    address3 CDATA #IMPLIED
    nextofkinname CDATA #IMPLIED
    nextofkinphone CDATA #IMPLIED
    race CDATA #IMPLIED
>

<!ELEMENT alternatepatientidentifier EMPTY>
<!ATTLIST alternatepatientidentifier
    id CDATA #REQUIRED
    identifier CDATA #IMPLIED
    patient CDATA #IMPLIED
    datechanged CDATA #IMPLIED
    masterpatientid CDATA #IMPLIED
    type_id CDATA #REQUIRED
>

<!ELEMENT appointment EMPTY>
<!ATTLIST appointment
    id CDATA #REQUIRED
    appointmentdate CDATA #IMPLIED
    patient CDATA #IMPLIED
    visitdate CDATA #IMPLIED
>

<!ELEMENT chemicalcompound EMPTY>
<!ATTLIST chemicalcompound
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    acronym CDATA #IMPLIED
>

<!ELEMENT atccode_chemicalcompound EMPTY>
<!ATTLIST atccode_chemicalcompound
    atccode_id CDATA #REQUIRED
    chemicalcompound_id CDATA #REQUIRED
>

<!ELEMENT attributetype EMPTY>
<!ATTLIST attributetype
    id CDATA #REQUIRED
    datatype CDATA #IMPLIED
    description CDATA #IMPLIED
    name CDATA #IMPLIED
>

<!ELEMENT campaign EMPTY>
<!ATTLIST campaign
    id CDATA #REQUIRED
    description CDATA #IMPLIED
    duration CDATA #IMPLIED
    name CDATA #REQUIRED
    startdate CDATA #IMPLIED
    status CDATA #REQUIRED
    timesperday CDATA #IMPLIED
    type CDATA #REQUIRED
    version CDATA #REQUIRED
    mobilisrid CDATA #IMPLIED
>

<!ELEMENT campaign_participant EMPTY>
<!ATTLIST campaign_participant
    campaign_id CDATA #REQUIRED
    patient_id CDATA #REQUIRED
    id CDATA #REQUIRED
>

<!ELEMENT chemicaldrugstrength EMPTY>
<!ATTLIST chemicaldrugstrength
    id CDATA #REQUIRED
    chemicalcompound CDATA #REQUIRED
    strength CDATA #IMPLIED
    drug CDATA #REQUIRED
>

<!ELEMENT clinicuser EMPTY>
<!ATTLIST clinicuser
    clinicid CDATA #REQUIRED
    userid CDATA #REQUIRED
>

<!ELEMENT databasechangelog EMPTY>
<!ATTLIST databasechangelog
    id CDATA #REQUIRED
    author CDATA #REQUIRED
    filename CDATA #REQUIRED
    dateexecuted CDATA #REQUIRED
    orderexecuted CDATA #REQUIRED
    exectype CDATA #REQUIRED
    md5sum CDATA #IMPLIED
    description CDATA #IMPLIED
    comments CDATA #IMPLIED
    tag CDATA #IMPLIED
    liquibase CDATA #IMPLIED
>

<!ELEMENT databasechangeloglock EMPTY>
<!ATTLIST databasechangeloglock
    id CDATA #REQUIRED
    locked CDATA #REQUIRED
    lockgranted CDATA #IMPLIED
    lockedby CDATA #IMPLIED
>

<!ELEMENT deleteditem EMPTY>
<!ATTLIST deleteditem
    id CDATA #REQUIRED
    deleteditemid CDATA #IMPLIED
    itemtype CDATA #IMPLIED
>

<!ELEMENT doctor EMPTY>
<!ATTLIST doctor
    id CDATA #REQUIRED
    emailaddress CDATA #IMPLIED
    firstname CDATA #IMPLIED
    lastname CDATA #IMPLIED
    mobileno CDATA #IMPLIED
    modified CDATA #IMPLIED
    telephoneno CDATA #IMPLIED
    active CDATA #IMPLIED
>

<!ELEMENT episode EMPTY>
<!ATTLIST episode
    id CDATA #REQUIRED
    startdate CDATA #REQUIRED
    stopdate CDATA #IMPLIED
    startreason CDATA #IMPLIED
    stopreason CDATA #IMPLIED
    startnotes CDATA #IMPLIED
    stopnotes CDATA #IMPLIED
    patient CDATA #IMPLIED
    index CDATA #IMPLIED
    clinic CDATA #REQUIRED
>

<!ELEMENT identifiertype EMPTY>
<!ATTLIST identifiertype
    id CDATA #REQUIRED
    name CDATA #REQUIRED
    index CDATA #IMPLIED
    voided CDATA #REQUIRED
>

<!ELEMENT logging EMPTY>
<!ATTLIST logging
    id CDATA #REQUIRED
    itemid CDATA #IMPLIED
    modified CDATA #IMPLIED
    transactiondate CDATA #IMPLIED
    transactiontype CDATA #IMPLIED
    idart_user CDATA #REQUIRED
    message CDATA #IMPLIED
>

<!ELEMENT messageschedule EMPTY>
<!ATTLIST messageschedule
    id CDATA #REQUIRED
    description CDATA #IMPLIED
    messagetype CDATA #REQUIRED
    scheduledate CDATA #REQUIRED
    daystoschedule CDATA #IMPLIED
    scheduledsuccessfully CDATA #IMPLIED
    senttoalerts CDATA #IMPLIED
    messagenumber CDATA #IMPLIED
    language CDATA #IMPLIED
>

<!ELEMENT packageddrugs EMPTY>
<!ATTLIST packageddrugs
    id CDATA #REQUIRED
    amount CDATA #IMPLIED
    stock CDATA #REQUIRED
    parentpackage CDATA #REQUIRED
    modified CDATA #IMPLIED
    packageddrugsindex CDATA #IMPLIED
>

<!ELEMENT users EMPTY>
<!ATTLIST users
    id CDATA #REQUIRED
    modified CDATA #IMPLIED
    cl_password CDATA #IMPLIED
    role CDATA #IMPLIED
    cl_username CDATA #IMPLIED
>

<!ELEMENT packagedruginfotmp EMPTY>
<!ATTLIST packagedruginfotmp
    id CDATA #REQUIRED
    amountpertime CDATA #IMPLIED
    batchnumber CDATA #IMPLIED
    clinic CDATA #IMPLIED
    dispensedate CDATA #IMPLIED
    dispensedqty CDATA #IMPLIED
    drugname CDATA #IMPLIED
    expirydate CDATA #IMPLIED
    formlanguage1 CDATA #IMPLIED
    formlanguage2 CDATA #IMPLIED
    formlanguage3 CDATA #IMPLIED
    notes CDATA #IMPLIED
    packageindex CDATA #IMPLIED
    patientid CDATA #IMPLIED
    patientfirstname CDATA #IMPLIED
    specialinstructions1 CDATA #IMPLIED
    specialinstructions2 CDATA #IMPLIED
    stockid CDATA #IMPLIED
    timesperday CDATA #IMPLIED
    cluser CDATA #REQUIRED
    weekssupply CDATA #IMPLIED
    sidetreatment CDATA #IMPLIED
    packageddrug CDATA #REQUIRED
    invalid CDATA #IMPLIED
    qtyinhand CDATA #IMPLIED
    summaryqtyinhand CDATA #IMPLIED
    qtyinlastbatch CDATA #IMPLIED
    patientlastname CDATA #IMPLIED
    prescriptionduration CDATA #IMPLIED
    dateexpectedstring CDATA #IMPLIED
    senttoekapa CDATA #IMPLIED
    packageid CDATA #IMPLIED
    firstbatchinprintjob CDATA #IMPLIED
    numberoflabels CDATA #IMPLIED
    dispensedforlaterpickup CDATA #IMPLIED
    pickupdate CDATA #IMPLIED
>

<!ELEMENT patientattribute EMPTY>
<!ATTLIST patientattribute
    id CDATA #REQUIRED
    value CDATA #IMPLIED
    patient CDATA #IMPLIED
    type_id CDATA #IMPLIED
>

<!ELEMENT patientidentifier EMPTY>
<!ATTLIST patientidentifier
    id CDATA #REQUIRED
    value CDATA #REQUIRED
    patient_id CDATA #REQUIRED
    type_id CDATA #REQUIRED
>

<!ELEMENT patientstatistic EMPTY>
<!ATTLIST patientstatistic
    id CDATA #REQUIRED
    entry_id CDATA #IMPLIED
    patient_id CDATA #IMPLIED
    datetested CDATA #IMPLIED
    daterecorded CDATA #IMPLIED
    patientstattype_id CDATA #IMPLIED
    statnumeric CDATA #IMPLIED
    stattext CDATA #IMPLIED
    statdate CDATA #IMPLIED
>

<!ELEMENT patientstattypes EMPTY>
<!ATTLIST patientstattypes
    id CDATA #REQUIRED
    statname CDATA #IMPLIED
    statformat CDATA #IMPLIED
>

<!ELEMENT patientvisit EMPTY>
<!ATTLIST patientvisit
    id CDATA #REQUIRED
    patient_id CDATA #IMPLIED
    dateofvisit CDATA #IMPLIED
    isscheduled CDATA #IMPLIED
    patientvisitreason_id CDATA #IMPLIED
    diagnosis CDATA #IMPLIED
    notes CDATA #IMPLIED
>

<!ELEMENT patientvisitreason EMPTY>
<!ATTLIST patientvisitreason
    id CDATA #REQUIRED
    reasonforvisit CDATA #IMPLIED
>

<!ELEMENT pregnancy EMPTY>
<!ATTLIST pregnancy
    id CDATA #REQUIRED
    confirmdate CDATA #IMPLIED
    enddate CDATA #IMPLIED
    patient CDATA #REQUIRED
    modified CDATA #IMPLIED
>

<!ELEMENT prescription EMPTY>
<!ATTLIST prescription
    id CDATA #REQUIRED
    clinicalstage CDATA #IMPLIED
    current CDATA #IMPLIED
    date CDATA #IMPLIED
    doctor CDATA #IMPLIED
    duration CDATA #IMPLIED
    modified CDATA #IMPLIED
    patient CDATA #REQUIRED
    prescriptionid CDATA #IMPLIED
    weight CDATA #IMPLIED
    reasonforupdate CDATA #IMPLIED
    notes CDATA #IMPLIED
    enddate CDATA #IMPLIED
    drugtypes CDATA #IMPLIED
>

<!ELEMENT prescribeddrugs EMPTY>
<!ATTLIST prescribeddrugs
    id CDATA #REQUIRED
    amtpertime CDATA #IMPLIED
    drug CDATA #IMPLIED
    prescription CDATA #IMPLIED
    timesperday CDATA #IMPLIED
    modified CDATA #IMPLIED
    prescribeddrugsindex CDATA #IMPLIED
>

<!ELEMENT regimen EMPTY>
<!ATTLIST regimen
    id CDATA #REQUIRED
    modified CDATA #IMPLIED
    notes CDATA #IMPLIED
    regimenname CDATA #IMPLIED
    druggroup CDATA #IMPLIED
>

<!ELEMENT regimendrugs EMPTY>
<!ATTLIST regimendrugs
    id CDATA #REQUIRED
    amtpertime CDATA #IMPLIED
    drug CDATA #IMPLIED
    modified CDATA #IMPLIED
    regimen CDATA #IMPLIED
    timesperday CDATA #IMPLIED
    notes CDATA #IMPLIED
    regimendrugsindex CDATA #IMPLIED
>

<!ELEMENT simpledomain EMPTY>
<!ATTLIST simpledomain
    id CDATA #REQUIRED
    description CDATA #IMPLIED
    name CDATA #IMPLIED
    value CDATA #IMPLIED
>

<!ELEMENT stockcenter EMPTY>
<!ATTLIST stockcenter
    id CDATA #REQUIRED
    stockcentername CDATA #IMPLIED
    preferred CDATA #IMPLIED
>

<!ELEMENT stock EMPTY>
<!ATTLIST stock
    id CDATA #REQUIRED
    drug CDATA #REQUIRED
    batchnumber CDATA #IMPLIED
    datereceived CDATA #IMPLIED
    stockcenter CDATA #REQUIRED
    expirydate CDATA #IMPLIED
    modified CDATA #IMPLIED
    shelfnumber CDATA #IMPLIED
    unitsreceived CDATA #IMPLIED
    manufacturer CDATA #IMPLIED
    hasunitsremaining CDATA #IMPLIED
    unitprice CDATA #IMPLIED
>

<!ELEMENT stocktake EMPTY>
<!ATTLIST stocktake
    id CDATA #REQUIRED
    enddate CDATA #IMPLIED
    startdate CDATA #IMPLIED
    stocktakenumber CDATA #IMPLIED
    open CDATA #IMPLIED
>

<!ELEMENT stockadjustment EMPTY>
<!ATTLIST stockadjustment
    id CDATA #REQUIRED
    capturedate CDATA #IMPLIED
    stock CDATA #REQUIRED
    notes CDATA #IMPLIED
    stocktake CDATA #IMPLIED
    stockcount CDATA #IMPLIED
    adjustedvalue CDATA #IMPLIED
    finalised CDATA #IMPLIED
>

<!ELEMENT stocklevel EMPTY>
<!ATTLIST stocklevel
    id CDATA #REQUIRED
    batch CDATA #REQUIRED
    fullcontainersremaining CDATA #IMPLIED
    loosepillsremaining CDATA #IMPLIED
>

<!ELEMENT study EMPTY>
<!ATTLIST study
    id CDATA #REQUIRED
    studyname CDATA #REQUIRED
>

<!ELEMENT studyparticipant EMPTY>
<!ATTLIST studyparticipant
    id CDATA #REQUIRED
    studygroup CDATA #REQUIRED
    startdate CDATA #REQUIRED
    enddate CDATA #IMPLIED
    patient CDATA #REQUIRED
    study CDATA #REQUIRED
    randomizationid CDATA #IMPLIED
    alternatecellphone CDATA #IMPLIED
    network CDATA #REQUIRED
    language CDATA #IMPLIED
>

=== openMRSiDART/iDART/target-test/datasets/testDataCombined.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "iDART.dtd">
<dataset>
  <atccode id="0" name="Metisazone" code="J05AA01"/>
  <atccode id="1" name="Aciclovir" code="J05AB01"/>
  <atccode id="2" name="Idoxuridine" code="J05AB02"/>
  <atccode id="3" name="Vidarabine" code="J05AB03"/>
  <atccode id="4" name="Ribavirin" code="J05AB04"/>
  <atccode id="5" name="Ganciclovir" code="J05AB06"/>
  <atccode id="6" name="Famciclovir" code="J05AB09"/>
  <atccode id="7" name="Valaciclovir" code="J05AB11"/>
  <atccode id="8" name="Cidofovir" code="J05AB12"/>
  <atccode id="9" name="Penciclovir" code="J05AB13"/>
  <atccode id="10" name="Valganciclov" code="J05AB14"/>
  <atccode id="11" name="Brivudine" code="J05AB15"/>
  <atccode id="12" name="Rimantadine" code="J05AC02"/>
  <atccode id="13" name="Tromantadine" code="J05AC03"/>
  <atccode id="14" name="Foscarnet" code="J05AD01"/>
  <atccode id="15" name="Fosfonet" code="J05AD02"/>
  <atccode id="16" name="Saquinavir" code="J05AE01"/>
  <atccode id="17" name="Indinavir" code="J05AE02"/>
  <atccode id="18" name="Ritonavir" code="J05AE03" mims="18.12"/>
  <atccode id="19" name="Nelfinavir" code="J05AE04" mims="19.12"/>
  <atccode id="20" name="Amprenavir" code="J05AE05"/>
  <atccode id="21" name="Lopinavir" code="J05AE06" mims="18.12"/>
  <atccode id="22" name="Fosamprenavir" code="J05AE07"/>
  <atccode id="23" name="Atazanavir" code="J05AE08"/>
  <atccode id="24" name="Tipranavir" code="J05AE09"/>
  <atccode id="25" name="Darunavir" code="J05AE10"/>
  <atccode id="26" name="Zidovudine" code="J05AF01" mims="18.12"/>
  <atccode id="27" name="Didanosine" code="J05AF02" mims="18.12"/>
  <atccode id="28" name="Zalcitabine" code="J05AF03"/>
  <atccode id="29" name="Stavudine" code="J05AF04" mims="18.12"/>
  <atccode id="30" name="Lamivudine" code="J05AF05" mims="18.9"/>
  <atccode id="31" name="Abacavir" code="J05AF06" mims="19.12"/>
  <atccode id="32" name="Tenofovir disoproxil" code="J05AF07" mims="18.12"/>
  <atccode id="33" name="Adefovir dipivoxil" code="J05AF08"/>
  <atccode id="34" name="Emtricitabine" code="J05AF09"/>
  <atccode id="35" name="Entecavir" code="J05AF10"/>
  <atccode id="36" name="Telbivudine" code="J05AF11"/>
  <atccode id="37" name="Clevudine" code="J05AF12"/>
  <atccode id="38" name="Nevirapine" code="J05AG01" mims="18.12"/>
  <atccode id="39" name="Delavirdine" code="J05AG02"/>
  <atccode id="40" name="Efavirenz" code="J05AG03" mims="19.12"/>
  <atccode id="41" name="Etravirine" code="J05AG04"/>
  <atccode id="42" name="Zanamivir" code="J05AH01"/>
  <atccode id="43" name="Oseltamivir" code="J05AH02"/>
  <atccode id="44" name="Zidovudine and Lamivudine" code="J05AR01"/>
  <atccode id="45" name="Lamivudine and Abacavir" code="J05AR02"/>
  <atccode id="46" name="Tenofovir disoproxil and Emtricitabine" code="J05AR03"/>
  <atccode id="47" name="Zidovudine, Lamivudine and Abacavir" code="J05AR04"/>
  <atccode id="48" name="Zidovudine, Lamivudine and Nevirapine" code="J05AR05"/>
  <atccode id="49" name="Emtricitabine, Tenofovir disoproxil and Efavirenz" code="J05AR06"/>
  <atccode id="50" name="Stavudine, Lamivudine and Nevirapine" code="J05AR07"/>
  <atccode id="51" name="Moroxydine" code="J05AX01"/>
  <atccode id="52" name="Lysozyme" code="J05AX02"/>
  <atccode id="53" name="Inosine pranobex" code="J05AX05"/>
  <atccode id="54" name="Pleconaril" code="J05AX06"/>
  <atccode id="55" name="Enfuvirtide" code="J05AX07"/>
  <atccode id="56" name="Raltegravir" code="J05AX08"/>
  <atccode id="57" name="Maraviroc" code="J05AX09"/>
  <atccode id="58" name="Maribavir" code="J05AX10"/>
  <form id="1" form="Lozenges" actionlanguage1="Suck" actionlanguage2="Munca" actionlanguage3="Suig" formlanguage1="lozenge(s)" formlanguage2="" formlanguage3="" dispinstructions1=""/>
  <form id="2" form="Cream" actionlanguage1="Apply" actionlanguage2="Qaba" actionlanguage3="Wend aan" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1=""/>
  <form id="3" form="Ointment" actionlanguage1="Apply" actionlanguage2="Qaba" actionlanguage3="Wend aan" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1=""/>
  <form id="4" form="Gel" actionlanguage1="Apply" actionlanguage2="Qaba" actionlanguage3="Wend aan" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1=""/>
  <form id="5" form="Oral Gel" actionlanguage1="Apply" actionlanguage2="Qaba" actionlanguage3="Wend aan" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1="to the mouth / emlonyeni"/>
  <form id="6" form="Lotion" actionlanguage1="Apply" actionlanguage2="Qaba" actionlanguage3="Wend aan" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1=""/>
  <form id="7" form="Vaginal Cream" actionlanguage1="Insert" actionlanguage2="Faka" actionlanguage3="Steek in" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1="Vaginal Cream / Isithambiso sangaphantsi"/>
  <form id="8" form="Eye Ointment" actionlanguage1="Apply" actionlanguage2="Qaba" actionlanguage3="Wend aan" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1="to __ eye(s)"/>
  <form id="9" form="Suppository" actionlanguage1="Insert" actionlanguage2="Faka" actionlanguage3="Steek in" formlanguage1="suppository" formlanguage2="" formlanguage3="" dispinstructions1=""/>
  <form id="10" form="Nose drops" actionlanguage1="Instill" actionlanguage2="Galela" actionlanguage3="Gebruik" formlanguage1="drops" formlanguage2="amathontsi" formlanguage3="druppel(s)" dispinstructions1="in each nostril"/>
  <form id="11" form="Eye drops" actionlanguage1="Instill" actionlanguage2="Galela" actionlanguage3="Gebruik" formlanguage1="drops" formlanguage2="amathontsi" formlanguage3="druppel(s)" dispinstructions1="in __ eye(s)"/>
  <form id="12" form="Ear drops" actionlanguage1="Instill" actionlanguage2="Galela" actionlanguage3="Gebruik" formlanguage1="drops" formlanguage2="amathontsi" formlanguage3="druppel(s)" dispinstructions1="in __ ear(s)"/>
  <form id="13" form="Soap" actionlanguage1="Wash with soap" actionlanguage2="Hlamba nge sepa" actionlanguage3="Was met seep" formlanguage1="" formlanguage2="" formlanguage3="" dispinstructions1=""/>
  <form id="14" form="Tablets" actionlanguage1="Take" actionlanguage2="Sela" actionlanguage3="Neem" formlanguage1="tablets" formlanguage2="ipilisi" formlanguage3="pille" dispinstructions1=""/>
  <form id="15" form="Suspension" actionlanguage1="Take" actionlanguage2="Sela" actionlanguage3="Neem" formlanguage1="ml" formlanguage2="ml" formlanguage3="ml" dispinstructions1=""/>
  <form id="16" form="Syrup" actionlanguage1="Take" actionlanguage2="Sela" actionlanguage3="Neem" formlanguage1="ml" formlanguage2="ml" formlanguage3="ml" dispinstructions1=""/>
  <form id="17" form="Capsules" actionlanguage1="Take" actionlanguage2="Sela" actionlanguage3="Neem" formlanguage1="capsules" formlanguage2="ipilisi" formlanguage3="pille" dispinstructions1=""/>
  <drug id="1" form="16" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[ABC] Abacavir 20mg/ml" packsize="240" sidetreatment="F" defaultamnt="0.0" defaulttimes="2" stockcode="" atccode_id="31"/>
  <drug id="2" form="14" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[ABC] Abacavir 300mg" packsize="60" sidetreatment="F" defaultamnt="1.0" defaulttimes="2" stockcode="" atccode_id="31"/>
  <drug id="3" form="14" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[TDF] Tenofovir 300mg" packsize="30" sidetreatment="F" defaultamnt="1.0" defaulttimes="1" stockcode="" atccode_id="32"/>
  <drug id="4" form="14" dispensinginstructions1="Take on an empty stomach" dispensinginstructions2="" modified="T" name="[DDI] Didanosine 25mg" packsize="60" sidetreatment="F" defaultamnt="0.0" defaulttimes="2" stockcode="" atccode_id="27"/>
  <drug id="5" form="14" dispensinginstructions1="Take on an empty stomach" dispensinginstructions2="" modified="T" name="[DDI] Didanosine 50mg" packsize="60" sidetreatment="F" defaultamnt="0.0" defaulttimes="2" stockcode="" atccode_id="27"/>
  <drug id="6" form="17" dispensinginstructions1="Take at night only" dispensinginstructions2="" modified="T" name="[EFV] Efavirenz 200mg" packsize="90" sidetreatment="F" defaultamnt="0.0" defaulttimes="1" stockcode="" atccode_id="40"/>
  <drug id="7" form="17" dispensinginstructions1="Take at night only" dispensinginstructions2="" modified="T" name="[EFV] Efavirenz 50mg" packsize="30" sidetreatment="F" defaultamnt="0.0" defaulttimes="1" stockcode="" atccode_id="40"/>
  <drug id="8" form="14" dispensinginstructions1="Take at night only" dispensinginstructions2="" modified="T" name="[EFV] Efavirenz 600mg" packsize="30" sidetreatment="F" defaultamnt="1.0" defaulttimes="1" stockcode="" atccode_id="40"/>
  <drug id="9" form="16" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[3TC] Lamivudine 10mg/ml" packsize="240" sidetreatment="F" defaultamnt="0.0" defaulttimes="2" stockcode="" atccode_id="30"/>
  <drug id="10" form="14" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[3TC] Lamivudine 150mg" packsize="60" sidetreatment="F" defaultamnt="1.0" defaulttimes="2" stockcode="" atccode_id="30"/>
  <drug id="11" form="14" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[NVP] Nevirapine 200mg" packsize="60" sidetreatment="F" defaultamnt="1.0" defaulttimes="2" stockcode="" atccode_id="38"/>
  <drug id="12" form="16" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[NVP] Nevirapine 50mg/5ml" packsize="240" sidetreatment="F" defaultamnt="0.0" defaulttimes="2" stockcode="" atccode_id="38"/>
  <drug id="13" form="16" dispensinginstructions1="" dispensinginstructions2="" modified="T" name="[RTV] Ritonavir 80mg/ml" packsize="90" sidetreatment="F" defaultamnt="0.0" defaulttimes="2" stockcode="" atccode_id="18"/>
